### ISSUE TITLE
Frontend Tasks

### ISSUE THREAD

**Issue by aditya-mitra** [kanishkguptagit/Kabootar#47]
- Remove **Filter By** and **Replace by organization names**

![image](https://user-images.githubusercontent.com/55396651/126371893-401569c9-d7c8-472c-8b63-379c01d4c9a3.png)

- Format **date** in scheduled column in History

- Add a button in compose email to the right of the editor.

**Comment by aditya-mitra** [comment]
https://camo.githubusercontent.com/9bd4de80a1b21666bab00a33c95dec3e7c599e807107fc16176931e0b64ffbe0/68747470733a2f2f63646e2e6472696262626c652e636f6d2f75736572732f3936333532372f73637265656e73686f74732f323938303538362f32303136303932332d332d3178697964356e2e6a70673f636f6d70726573733d3126726573697a653d38303078363030

**Comment by kanishkguptagit** [comment]
layout refactoring

**Comment by aditya-mitra** [comment]
Sent Mails, Opened Mails, Clicked Mails

![image](https://user-images.githubusercontent.com/55396651/126373175-ea822f07-054a-4f63-8f18-a979c9b2978a.png)

**Comment by kanishkguptagit** [comment]
![image](https://user-images.githubusercontent.com/56789607/126845632-05d3b201-a91c-4dc8-ba40-d2dcc263e253.png)

**Comment by aditya-mitra** [comment]
only the `datesSent` part is left
